### ISSUE TITLE
Problem in string parser for boat drop

### ISSUE THREAD

**Issue by smartaleq** [smartaleq/DwarfCraft_orig#1]
Effect.java line 271 in "if effectType.vehicleDrop" section of code

java.util.IllegalFormatConversionException: f != java.lang.String
        at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4011)
        at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2738)
        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2683)
        at java.util.Formatter.format(Formatter.java:2449)
        at java.util.Formatter.format(Formatter.java:2383)
        at java.lang.String.format(String.java:2781)
        at com.smartaleq.bukkit.dwarfcraft.Effect.describeLevel(Effect.java:271)
        at com.smartaleq.bukkit.dwarfcraft.ui.Out.printSkillInfo(Out.java:89)

**Comment by RCarretta** [comment]
Caused by a missing %s identifier
Old:
"&6When you break a boat &6approx. %s%.2f &2%s&6 are created"

New:
&6When you break a boat &6approx. %s%s%.2f &2%s&6 are created"
