### ISSUE TITLE
string formatting exception in effectInfo

### ISSUE THREAD

**Issue by RCarretta** [smartaleq/DwarfCraft_orig#10]
2011-02-21 01:37:53 [SEVERE] Could not pass event PLAYER_COMMAND to DwarfCraft
java.util.UnknownFormatConversionException: Conversion = 'F'
        at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2622)
        at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2650)
        at java.util.Formatter.parse(Formatter.java:2496)
        at java.util.Formatter.format(Formatter.java:2430)
        at java.util.Formatter.format(Formatter.java:2383)
        at java.lang.String.format(String.java:2781)
        at com.smartaleq.bukkit.dwarfcraft.Effect.describeGeneral(Effect.java:120)
        at com.smartaleq.bukkit.dwarfcraft.ui.Out.effectInfo(Out.java:139)
        at com.smartaleq.bukkit.dwarfcraft.ui.Command.effectInfo(Command.java:197)
        at com.smartaleq.bukkit.dwarfcraft.ui.Command.execute(Command.java:71)
        at com.smartaleq.bukkit.dwarfcraft.DCPlayerListener.onPlayerCommand(DCPlayerListener.java:40)
        at org.bukkit.plugin.java.JavaPluginLoader$5.execute(JavaPluginLoader.java:150)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:59)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:225)
        at net.minecraft.server.NetServerHandler.c(NetServerHandler.java:650)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:601)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:593)
        at net.minecraft.server.Packet3Chat.a(SourceFile:24)
        at net.minecraft.server.NetworkManager.a(SourceFile:232)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:78)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:104)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:325)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:240)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:512)
2011-02-21 01:37:53 [INFO] smartaleq issued server command: dc effectinfo 132

**Comment by RCarretta** [comment]
Fixed.
