### ISSUE TITLE
exception thrown on /dc reallymakemeanelf

### ISSUE THREAD

**Issue by RCarretta** [smartaleq/DwarfCraft_orig#6]
2011-02-20 23:07:39 [SEVERE] Could not pass event PLAYER_COMMAND to DwarfCraft
java.lang.NoClassDefFoundError: com/smartaleq/bukkit/dwarfcraft/ui/Messages
        at com.smartaleq.bukkit.dwarfcraft.ui.Out.becameAnElf(Out.java:147)
        at com.smartaleq.bukkit.dwarfcraft.ui.Command.makeMeAnElf(Command.java:336)
        at com.smartaleq.bukkit.dwarfcraft.ui.Command.execute(Command.java:79)
        at com.smartaleq.bukkit.dwarfcraft.DCPlayerListener.onPlayerCommand(DCPlayerListener.java:40)
        at org.bukkit.plugin.java.JavaPluginLoader$5.execute(JavaPluginLoader.java:150)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:59)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:225)
        at net.minecraft.server.NetServerHandler.c(NetServerHandler.java:650)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:601)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:593)
        at net.minecraft.server.Packet3Chat.a(SourceFile:24)
        at net.minecraft.server.NetworkManager.a(SourceFile:232)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:78)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:104)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:325)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:240)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:512)
Caused by: java.lang.ClassNotFoundException: com.smartaleq.bukkit.dwarfcraft.ui.Messages
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:30)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:336)
        ... 17 more

**Comment by RCarretta** [comment]
Joey fixed this already.
