### ISSUE TITLE
exception thrown when more than 10 arguments passed to /dc

### ISSUE THREAD

**Issue by RCarretta** [smartaleq/DwarfCraft_orig#8]
2011-02-20 23:57:33 [SEVERE] Could not pass event PLAYER_COMMAND to DwarfCraft
java.lang.ArrayIndexOutOfBoundsException: 10
        at com.smartaleq.bukkit.dwarfcraft.DCPlayerListener.onPlayerCommand(DCPlayerListener.java:37)
        at org.bukkit.plugin.java.JavaPluginLoader$5.execute(JavaPluginLoader.java:150)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:59)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:225)
        at net.minecraft.server.NetServerHandler.c(NetServerHandler.java:650)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:601)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:593)
        at net.minecraft.server.Packet3Chat.a(SourceFile:24)
        at net.minecraft.server.NetworkManager.a(SourceFile:232)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:78)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:104)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:325)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:240)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:512)
2011-02-20 23:57:33 [INFO] veratio tried command: dc setskill j j j j j j j j j j j j j j j j

**Comment by RCarretta** [comment]
Fixed. Dynamically size array on creation based on cmd typed.
