### ISSUE TITLE
v1.04 Cannot pass events

### ISSUE THREAD

**Issue by clc02** [smartaleq/DwarfCraft_orig#82]
In version 1.04 on a fresh install the server will do
Cannot pass event PLAYER_JOIN when a player joins and
Cannot pass event BLOCK_DAMAGED when they damage a block.

Errors:

[SEVERE] Could not pass event PLAYER_JOIN to DwarfCraft
java.lang.NullPointerException
    at com.smartaleq.bukkit.dwarfcraft.ConfigManager.getAllSkills(ConfigManager.java:67)
    at com.smartaleq.bukkit.dwarfcraft.DCPlayer.changeRace(DCPlayer.java:342)
    at com.smartaleq.bukkit.dwarfcraft.DataManager.createDwarf(DataManager.java:156)
    at com.smartaleq.bukkit.dwarfcraft.DCPlayerListener.onPlayerJoin(DCPlayerListener.java:75)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:162)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:59)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:255)
    at net.minecraft.server.ServerConfigurationManager.a(ServerConfigurationManager.java:98)
    at net.minecraft.server.NetLoginHandler.b(NetLoginHandler.java:87)
    at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:27)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:87)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:357)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:272)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)

2011-03-24 15:43:25 [SEVERE] Could not pass event BLOCK_DAMAGED to DwarfCraft
java.lang.NullPointerException
    at com.smartaleq.bukkit.dwarfcraft.DCBlockListener.onBlockDamage(DCBlockListener.java:122)
    at org.bukkit.plugin.java.JavaPluginLoader$22.execute(JavaPluginLoader.java:269)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:59)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:255)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:358)
    at net.minecraft.server.Packet14BlockDig.a(SourceFile:42)
    at net.minecraft.server.NetworkManager.a(SourceFile:230)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:76)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:100)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:357)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:272)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)

2011-03-24 15:43:26 [SEVERE] Could not pass event BLOCK_BREAK to DwarfCraft
java.lang.NullPointerException
    at com.smartaleq.bukkit.dwarfcraft.DCBlockListener.onBlockBreak(DCBlockListener.java:38)
    at org.bukkit.plugin.java.JavaPluginLoader$30.execute(JavaPluginLoader.java:309)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:59)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:255)
    at net.minecraft.server.ItemInWorldManager.d(ItemInWorldManager.java:112)
    at net.minecraft.server.ItemInWorldManager.b(ItemInWorldManager.java:77)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:370)
    at net.minecraft.server.Packet14BlockDig.a(SourceFile:42)
    at net.minecraft.server.NetworkManager.a(SourceFile:230)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:76)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:100)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:357)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:272)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)

2011-03-24 15:43:27 [SEVERE] Could not pass event BLOCK_RIGHTCLICKED to DwarfCraft
java.lang.NullPointerException
    at com.smartaleq.bukkit.dwarfcraft.DCBlockListener.onBlockRightClick(DCBlockListener.java:174)
    at org.bukkit.plugin.java.JavaPluginLoader$20.execute(JavaPluginLoader.java:259)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:59)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:255)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:493)
    at net.minecraft.server.Packet15Place.a(SourceFile:57)
    at net.minecraft.server.NetworkManager.a(SourceFile:230)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:76)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:100)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:357)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:272)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)

**Comment by smartaleq** [comment]
did you update your craftbukkit? the most recent release completely changed those events. roll back to 556 or earlier recommended builds.

**Comment by clc02** [comment]
It actually worked with the same version that I had the previous version working on, then I figured it might of needed the newer one and upgraded to that and checked it.  I'll try.

**Comment by clc02** [comment]
I can confirm on b566 that it has same error
